const bateaux = [
    {
        id: 1,
        titre: "Bateau Moteur - 2022",
        image1: "images/moteur1.png",
        image2: "images/moteur2.png",
        personnes: "3 personnes",
        cabines: "1 cabines",
        longueur: "6 mètres",
        prix: "1695€/semaine",
        port: "Vannes",
        categorie: "moteur",
    },
    {
        id: 2,
        titre: "Lagoon 42 - 2020",
        image1: "images/catamaran1.png",
        image2: "images/catamaran2.png",
        prix: "3995€/semaine",
        port: "Brest",
        personnes: "12 pers",
        cabines: "5 cabines",
        longueur: "21m",
        categorie: "voile",
    },
    {
        id: 3,
        titre: "Bateau à voile",
        image1: "images/bateau-voile1.png",
        image2: "images/bateau-voile2.png",
        prix: "3695€/semaine",
        port: "Concarneau",
        personnes: "8 pers",
        cabines: "3 cabines",
        longueur: "35m",
        categorie: "voile",
    }
];